# ~/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
# format = """
# $directory$git_branch$git_state$package"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
command_timeout = 5000

# Disable the blank line at the start of the prompt
add_newline = false

# [directory]
# truncation_length = 5
# truncate_to_repo = false
# truncation_symbol = "…/"
# format = "[$path]($style)[$read_only]($read_only_style) "
# style = ""

# [package]
# format = "[📦$version]($style)[\ue0b0](red)"
# style = "bold fg:white bg:red"

# [git_branch]
# format = "[$symbol$branch]($style)[\ue0b0](fg:purple)"
# style = "bold fg:white bg:purple"

# Full Block: █
# Pairs: [, ], [, ], [, ], [, ], [, ]
# Top Bottom Boundary: ╭, ╰

# format = """$docker_context$username$directory$git_branch$git_status$git_state$git_commit$git_state$package$nodejs$python$rust$golang$memory_usage>${fill}<$cmd_duration$time\u001b8\n$character"""
format = """╭$username$docker_context$directory$git_branch$git_status$git_state$git_commit$git_state$package$nodejs$dotnet$python$rust${custom.qgl}$golang$fill\n╰$time $cmd_duration $character"""

# continuation_prompt = "\u001b7|\n\u001b8+"
# continuation_prompt = "\\033\\[1A"

[fill]
style = "bg:prev_bg"
symbol = " "

[cmd_duration]
style = "white"
min_time = 1
format = "[$duration]($style)"

[time]
disabled = false
format = '$time'
time_format = "%l:%M%P"

[character]
success_symbol = "[](fg:#B1FF8F bg:prev_bg)[](#B1FF8F)"
error_symbol = "[](fg:#FF8582 bg:prev_bg)[](#FF8582)"

[memory_usage]
style = "white"
symbol = "󰍛 "
format = "[](fg:prev_bg bg:$style)[ $symbol$ram_pct ](bg:$style fg:black)"
threshold = 2
disabled = false

[directory]
style = "#67b0ff"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[](fg:$style bg:prev_bg)[ $path$read_only ](bg:$style fg:black)"
read_only = " "

[docker_context]
style = "fg:black bg:#eb9606"
symbol = "🐳"
format = "[$symbol$context]($style)"

[git_branch]
style = "#f05133"
format = "[](fg:$style bg:prev_bg)[ $symbol$branch](fg:black bg:$style)"

[git_commit]
style = "#f05133"
format = "[](fg:$style bg:prev_bg)[ \\($hash$tag\\)](fg:black bg:$style)"

[git_state]
style = "#f05133"
format = "[](fg:$style bg:prev_bg)[ ($state($progress_current/$progress_total))](fg:black bg:$style)"

[git_status]
style = "#f05133"
format = "([$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind ](fg:black bg:$style))"
conflicted = "    ${count}"
staged = "  $count"
modified = "  ${count}"
renamed = "  ${count}"
deleted = "  ${count}"
untracked = "  ${count}"
stashed = "  ${count}"
ahead = "  ${count}"
behind = "  ${count}"
diverged = " 󱓌  ${ahead_count}  ${behind_count} "

[golang]
symbol = " "
style = "#77e7ff"
format = "[](fg:$style bg:prev_bg)[ $symbol$version](fg:black bg:$style)"

[nodejs]
symbol = "󰎙 "
style = "#aef27f"
format = "[](fg:$style bg:prev_bg)[ $symbol($version) ](fg:black bg:$style)"

[package]
disabled = true
style = "#eb9606"
format = "[](fg:$style bg:prev_bg)[ $symbol$version](fg:black bg:$style)"

[python]
symbol = "󰌠 "
style = "#ffde57"
format = "[](fg:$style bg:prev_bg)[ $symbol$pyenv_prefix$version$virtualenv](fg:black bg:$style)"

[dotnet]
symbol = " "
style = "#5026b5"
format = "[](fg:$style bg:prev_bg)[ $symbol$version $tfm](fg:white bg:$style)"

[rust]
symbol="󱘗 "
style = "#4b4945"
format = "[](fg:$style bg:prev_bg)[ $symbol$version](fg:white bg:$style)"

[username]
show_always = true
format = "[ $user ](fg:white)"

[custom.qgl]
# when = "qgl prompt"
detect_files = ["Build.xml"]
symbol = "QGL"
command = "qgl prompt"
style = "#371ee1"
format = "[](fg:$style bg:prev_bg)[ $symbol $output ](fg:white bg:$style)"
