# ~/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
# format = """
# $directory$git_branch$git_state$package"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
command_timeout = 5000

# Disable the blank line at the start of the prompt
add_newline = false

# [directory]
# truncation_length = 5
# truncate_to_repo = false
# truncation_symbol = "…/"
# format = "[$path]($style)[$read_only]($read_only_style) "
# style = ""

# [package]
# format = "[📦$version]($style)[\ue0b0](red)"
# style = "bold fg:white bg:red"

# [git_branch]
# format = "[$symbol$branch]($style)[\ue0b0](fg:purple)"
# style = "bold fg:white bg:purple"

# Full Block: █
# Pairs: [, ], [, ], [, ], [, ], [, ]
# Top Bottom Boundary: ╭, ╰

# format = """$docker_context$username$directory$git_branch$git_status$git_state$git_commit$git_state$package$nodejs$python$rust$golang$memory_usage>${fill}<$cmd_duration$time\u001b8$character"""
# $memory_usage
# Beginning: \u001b7 end: \u001b8 
format = """$docker_context$username$directory$git_branch$git_status$git_state$git_commit$git_state$package$nodejs$python$rust$golang[](fg:#f78a40 bg:white)[>\u001b7${fill}<](fg:white)\u001b8$cmd_duration$time\n$character"""
# continuation_prompt = "\u001b7|\n\u001b8+"
# continuation_prompt = "\\033\\[1A"

[fill]
style = "white"
symbol = "-"

[cmd_duration]	
style = "fg:black bg:white"
min_time = 1
format = "[ 󰔚 $duration ]($style)"

[time]
disabled = false
style = "fg:black bg:white"
format = '[$time  ]($style)'
time_format = "%l:%M %p"

[character]
success_symbol = "[██    ](fg:black bg:#B1FF8F)[](#B1FF8F)"
error_symbol = "[██    ](fg:black bg:#FF8582)[](#FF8582)"

[memory_usage]
style = "white"
symbol = "󰍛 "
format = "[](fg:#f78a40 bg:$style)[ $symbol$ram_pct ](bg:$style fg:black)"
threshold = 2
disabled = false

[directory]
style = "#67b0ff"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[](fg:$style bg:black)[ $path$read_only ](bg:$style fg:black)[](fg:$style bg:#f78a40)"
read_only = " "

[docker_context]
style = "fg:black bg:#eb9606"
symbol = "🐳"
format = "[$symbol$context]($style)"

[git_branch]
style = "#f78a40"
format = "[ $symbol$branch ](fg:black bg:$style)"

[git_commit]
style = "#f78a40"
format = "[\\($hash$tag\\)](fg:black bg:$style)"

[git_state]
style = "#f78a40"
format = "[($state($progress_current/$progress_total))](fg:black bg:$style)"

[git_status]
style = "#f78a40"
format = "([$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind ](fg:black bg:$style))"
conflicted = "    ${count} "
staged = "  $count"
modified = "  ${count}"
renamed = "  ${count}"
deleted = "  ${count}"
untracked = " ?${count}"
stashed = "  ${count}"
ahead = "  ${count}"
behind = "  ${count}"
diverged = " נּ  ${ahead_count}  ${behind_count} "

[golang]
symbol = " "
style = "fg:black bg:blue"
format = "[ ](fg:#f78a40 bg:$style)[$symbol$version]($style)[](fg:$style bg:#f78a40)"

[nodejs]
symbol = "󰎙 "
style = "#aef27f"
format = "[ ](fg:#f78a40 bg:$style)[ $symbol($version) ](fg:black bg:$style)[](fg:$style bg:#f78a40)"

[package]
disabled = true
style = "#eb9606"
format = "[ ](fg:#f78a40 bg:$style)[$symbol$version](fg:black bg:$style)[](fg:$style bg:#f78a40)"

[python]
symbol = "󰌠 "
style = "blue"
format = "[ ](fg:#f78a40 bg:$style)[$symbol$pyenv_prefix$version$virtualenv](fg:fg:black bg:$style)[](fg:$style bg:#f78a40)"

[rust]
symbol="󱘗 "
style = "#f74c00"
format = "[ ](fg:#f78a40 bg:$style)[$symbol$version](fg:black bg:$style)[](fg:$style bg:#f78a40)"

[username]
show_always = true
style_user = "black"
style_root = "black" # #FF8888
format = "[ $user ](fg:white bg:$style)"
